- name: Run Terraform
  block:
        - name: Execute Terraform Apply
          command: "terraform apply -auto-approve"
          args:
            chdir: "{{ terrafom_folder }}"
  tags: [provision]